server:
  port: 8082 #服务端口
spring:
  application:
    name: user-web

eureka:
  client:
    register-with-eureka: true  #服务注册开关
    fetch-registry: true #服务发现开关
    serviceUrl:
      defaultZone: ${eureka.url:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

#rocketmq consumer
rocketmq:
  consumer:
    isOnOff: ${queue.isOnOff:true}
    groupName: ${spring.application.name}
    nameSrvAddr: ${queue.ip:127.0.0.1}:${queue.port:9876}
    topic: ${queue.topic:test}
    tag: ${queue.tag:*}
    consumeThreadMin: ${queue.consumeThreadMin:10}
    consumeThreadMax: ${queue.consumeThreadMax:64}
    consumeMessageBatchMaxSize: ${queue.consumeMessageBatchMaxSize:1}

swagger:
  enable: true

